/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CapaPresentacion;

import CapaEntidades.EntidadClientes;
import CapaEntidades.EntidadDetalleFacturas;
import CapaEntidades.EntidadFacturaClientes;
import CapaEntidades.EntidadProductos;
import CapaLogica.BLClientes;
import CapaLogica.BLFacturaClientes;
import CapaLogica.BLProductos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;


/**
 *
 * @author gabri
 */
public class FrmFacturas extends javax.swing.JInternalFrame {
DefaultTableModel modelo;
    /**
     * Creates new form FrmFacturas
     */
  ArrayList<EntidadDetalleFacturas> lista = new ArrayList();
  
    public FrmFacturas() {
        initComponents();
        txtPrecio.setVisible(false);
        LimpiarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new javax.swing.JButton();
        btnGenerarFactura = new javax.swing.JButton();
        jLabelIdTipoFactura = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        jLabelTelefono2 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        cbmTipoFactura = new javax.swing.JComboBox<>();
        txtIdProducto = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabelNombreProducto = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        txtSubTotal = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jLabelSubTotal = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jTextFacturacion = new javax.swing.JTextField();

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGenerarFactura.setBackground(new java.awt.Color(51, 153, 0));
        btnGenerarFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarFactura.setText("Generar");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });

        jLabelIdTipoFactura.setText("Tipo Factura");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFactura);

        jLabelTelefono2.setText("Cantidad");

        txtIdCliente.setEditable(false);

        jLabelNombre.setText("Nombre");

        btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cbmTipoFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura Normal", "Orden De Reparación", "Proforma", " " }));
        cbmTipoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmTipoFacturaActionPerformed(evt);
            }
        });

        txtIdProducto.setEditable(false);
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });

        jLabelID.setText("ID Cliente");

        jLabelNombreProducto.setText("Nombre");

        txtNombre.setEditable(false);

        txtNombreProducto.setEditable(false);
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });

        jLabelCedula.setText("ID Producto");

        btnBuscarCliente.setBackground(new java.awt.Color(0, 51, 255));
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnBuscarProducto.setBackground(new java.awt.Color(0, 51, 255));
        btnBuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnAgregarProducto.setBackground(new java.awt.Color(51, 153, 0));
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        txtSubTotal.setEditable(false);

        txtTotal.setEditable(false);

        jLabelTotal.setText("Total");

        jLabelSubTotal.setText("Subtotal");

        txtPrecio.setEditable(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jTextFacturacion.setEditable(false);
        jTextFacturacion.setBackground(new java.awt.Color(153, 153, 153));
        jTextFacturacion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jTextFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        jTextFacturacion.setText("Facturación");
        jTextFacturacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSubTotal)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 101, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelCedula)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBuscarCliente))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBuscarProducto)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabelNombreProducto))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabelNombre)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(cbmTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelIdTipoFactura)
                                        .addGap(11, 11, 11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTelefono2)
                                        .addGap(34, 34, 34)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarProducto)))))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jTextFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(cbmTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelIdTipoFactura))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula)
                    .addComponent(jLabelNombreProducto)
                    .addComponent(jLabelTelefono2))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSubTotal)
                    .addComponent(jLabelTotal)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    private EntidadFacturaClientes GenerarEntidad(){
        EntidadFacturaClientes factura = new EntidadFacturaClientes();

                //mpresa.setId(Integer.parseInt(txtId.getText()));
                factura.setIdEmpresa(1);
                factura.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
                factura.setIdUsuario(FrmMenu.miUsuario.getId());
              //usuarios.setEstado(Boolean.valueOf(txtEstado.getText()));
                factura.setDescuento(0);
                factura.setTotal(Float.parseFloat(txtTotal.getText()));
                factura.setListaDetalles(lista);
                
                if(cbmTipoFactura.getSelectedItem().toString().equals("Factura Normal")){
                factura.setIdTipoFactura(1);  
                }                
                else if(cbmTipoFactura.getSelectedItem().toString().equals("Orden De Reparación")){
                factura.setIdTipoFactura(2);
                }                
                else if(cbmTipoFactura.getSelectedItem().toString().equals("Proforma")){
                factura.setIdTipoFactura(3);
                }
                   
        return factura;
         }
   
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //Limpiar La tabla
        
                Limpiar();
    }                                          
    
            public void    Limpiar(){
            txtIdCliente.setText(null);
            txtIdProducto.setText(null);
            txtNombre.setText(null);
            txtNombreProducto.setText(null);
            txtCantidad.setText(null);
            txtSubTotal.setText(null);
            txtTotal.setText(null);
            LimpiarTabla();
            lista = new ArrayList<>();            
       
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
   // Accion para generar la factura
        if(!txtIdCliente.getText().equals("")){
           
            if(lista.size() >= 1){
                BLFacturaClientes logica = new BLFacturaClientes();
                EntidadFacturaClientes factura = GenerarEntidad();
                try {
                    logica.Insertar(factura);            
                    Limpiar();
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "ERROR " + ex.getMessage());
                } 
            }else
                JOptionPane.showMessageDialog(null, "Debe de ingresar un item como minimo");
            
        }else
          JOptionPane.showMessageDialog(null, "Debe de seleccionar un cliente");
        
 
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    
    
    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void tblFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacturaMouseClicked
    if (evt.getClickCount() == 2)
    {
        if (JOptionPane.showConfirmDialog(rootPane, "Está seguro que desea eliminar este producto, ¿desea continuar?",
        "Eliminar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            if(lista != null){                
                int fila = tblFactura.rowAtPoint(evt.getPoint());
                int idProd = 0;
                ArrayList<EntidadDetalleFacturas> lista2 = lista;
                for (EntidadDetalleFacturas det : lista2)
                {
                    idProd = Integer.parseInt(tblFactura.getValueAt(fila, 0).toString());
                    if (det.getIdProducto() == idProd)
                    {
                     lista.remove(det);
                      break;
                    }
                 }
              LimpiarTabla();
              cargarTable();
            } 
        }
    }        
        
    }//GEN-LAST:event_tblFacturaMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // BUSCA EL CLIENTE 
        
         FrmBuscarClientes buscar = new FrmBuscarClientes(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    BLClientes logica = new BLClientes();
                    EntidadClientes usuarios;
                    if (id > -1) {
                        condicion = String.format("estado = 1 and Id=%d", id);
                        usuarios = logica.ObtenerUnCliente(condicion);
                        txtIdCliente.setText(String.valueOf(usuarios.getId()));
                        txtNombre.setText(usuarios.getNombre());       
                    }
                    else{
                        txtIdCliente.setText(null);
                        txtNombre.setText(null);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
        buscar.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void cbmTipoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmTipoFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmTipoFacturaActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // Buscar Producto 
        
        FrmBuscarProductos buscar = new FrmBuscarProductos(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    BLProductos logica = new BLProductos();
                    EntidadProductos producto;
                    if (id > -1) {
                        condicion = String.format("estado = 1 and Id=%d", id);
                        producto = logica.ObtenerUnProducto(condicion);
                        txtIdProducto.setText(String.valueOf(producto.getId()));
                        txtNombreProducto.setText(producto.getDescripcion());
                        txtPrecio.setText(String.valueOf(producto.getPrecioVenta()));
                    }
                    else{
                        txtIdProducto.setText(null);
                        txtNombreProducto.setText(null);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
        buscar.setVisible(true);
        
        
        
        
        
        
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

   private static boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
}
   
   public boolean validarExistencia(int idProducto){
       
       boolean ok = false;
       for (EntidadDetalleFacturas det : lista) {
            if (det.getIdProducto() == idProducto){
                ok = true;
                     break;
                 }
         }
       return ok;
   }
   
  
    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
      
        if(!txtIdProducto.getText().equals("") && !txtCantidad.getText().equals("")  )
        {
            if(isNumeric(txtCantidad.getText()))
            {
                if(Float.parseFloat(txtCantidad.getText()) > 0)
            {
                LimpiarTabla();
                EntidadDetalleFacturas detalle = new EntidadDetalleFacturas();

               detalle.setIdProducto(Integer.parseInt(txtIdProducto.getText()));
               detalle.setCantidad(Float.parseFloat(txtCantidad.getText()));
               detalle.setPrecioVenta(Float.parseFloat(txtPrecio.getText()));
               detalle.setNombre(txtNombreProducto.getText());
               detalle.setTotal(Float.parseFloat(txtPrecio.getText())*Float.parseFloat(txtCantidad.getText()));
               detalle.setDescuento(0);
              Boolean ok = validarExistencia(Integer.parseInt(txtIdProducto.getText()));
               if(ok)
                {
                    Integer cont = 0;
                     ArrayList<EntidadDetalleFacturas> lista2 = lista;
                    for (EntidadDetalleFacturas det : lista2) {
                        if (det.getIdProducto() == Integer.parseInt(txtIdProducto.getText())){
                        det.setCantidad(det.getCantidad() + Float.parseFloat(txtCantidad.getText()));
                        det.setTotal(det.getTotal()+ Float.parseFloat(txtPrecio.getText())* Float.parseFloat(txtCantidad.getText()));
                          lista2.set(cont, det);
                             break;
                         }
                        cont ++;
                    }
                 }else
                  lista.add(detalle);    
               
                cargarTable();

                try {
                
                } catch (Exception ex) {
                     JOptionPane.showMessageDialog(this, ex.getMessage());
                }    

                txtIdProducto.setText("");
                txtNombreProducto.setText("");
                txtCantidad.setText("");
              }
            else
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0");
            }
            else
                JOptionPane.showMessageDialog(this, "La cantidad debe ser un numero");
     } 
        else
            JOptionPane.showMessageDialog(this, "Faltan datos por completar");
    }//GEN-LAST:event_btnAgregarProductoActionPerformed
   
    public void cargarTable(){
        
    Object[] fila = new Object[6];
       float total = 0;
           float descuento = 0;
             for (EntidadDetalleFacturas det : lista) {
                 fila[0] = det.getIdProducto();
                 fila[1] = det.getNombre();
                 fila[2] = det.getPrecioVenta();
                 fila[3] = det.getCantidad();
                 fila[4] = det.getDescuento();
                 fila[5] = det.getTotal();
                 total += det.getTotal();
                 descuento += det.getDescuento();
                 modelo.addRow(fila);
             }
             txtTotal.setText(String.valueOf(total));
             txtSubTotal.setText(String.valueOf(total - descuento));
    }
    
    private void LimpiarTabla(){
        modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };     
        tblFactura.setModel(modelo);
        modelo.addColumn("Id Producto");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio Venta");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Total Descuento");
        modelo.addColumn("Total");
    }
    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbmTipoFactura;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIdTipoFactura;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JLabel jLabelSubTotal;
    private javax.swing.JLabel jLabelTelefono2;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFacturacion;
    private javax.swing.JTable tblFactura;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
