/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaEntidades.EntidadUsuarios;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gabri
 */
public class FrmMenu extends javax.swing.JFrame {

    public static EntidadUsuarios miUsuario = new EntidadUsuarios();
    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mnuempresa = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jFacturacion = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        escritorio.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpg"))); // NOI18N

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(57, 33));

        menu.setText("Menú");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        mnuempresa.setText("Empresas");
        mnuempresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuempresaMouseClicked(evt);
            }
        });
        mnuempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuempresaActionPerformed(evt);
            }
        });
        menu.add(mnuempresa);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        menu.add(mnuUsuarios);

        jMenuItem1.setText("Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem1);

        jMenuItem2.setText("Proveedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem2);

        jMenuItem3.setText("Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem3);

        jFacturacion.setText("Facturacion");
        jFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFacturacionActionPerformed(evt);
            }
        });
        menu.add(jFacturacion);

        jMenuItem4.setText("Vehiculos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem4);

        jMenuItem5.setText("Ventas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem5);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        FrmVentas frmve;
        try {
            frmve = new FrmVentas();

            escritorio.add(frmve);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmve.getSize();
            frmve.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmve.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        FrmVehiculos frmve;
        try {
            frmve = new FrmVehiculos();

            escritorio.add(frmve);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmve.getSize();
            frmve.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmve.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFacturacionActionPerformed

        FrmFacturas frmfac;
        try {
            frmfac = new FrmFacturas();

            escritorio.add(frmfac);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmfac.getSize();
            frmfac.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmfac.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jFacturacionActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        FrmClientes frmclie;
        try {
            frmclie = new FrmClientes();

            escritorio.add(frmclie);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmclie.getSize();
            frmclie.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmclie.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        FrmProveedores frmprovee;
        try {
            frmprovee = new FrmProveedores();

            escritorio.add(frmprovee);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmprovee.getSize();
            frmprovee.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmprovee.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        FrmProductos frmprodu;
        try {
            frmprodu = new FrmProductos();

            escritorio.add(frmprodu);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmprodu.getSize();
            frmprodu.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmprodu.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed

        FrmUsuarios frmusua;
        try {
            frmusua = new FrmUsuarios();

            escritorio.add(frmusua);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmusua.getSize();
            frmusua.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmusua.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuempresaActionPerformed

        FrmEmpresas frmemp;
        try {
            frmemp = new FrmEmpresas();

            escritorio.add(frmemp);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmemp.getSize();
            frmemp.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmemp.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mnuempresaActionPerformed

    private void mnuempresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuempresaMouseClicked

        FrmEmpresas frmemp;
        try {
            frmemp = new FrmEmpresas();
            escritorio.add(frmemp);
            //Centrar formulario
            Dimension sizeContenedor = escritorio.getSize();
            Dimension sizeFrm = frmemp.getSize();
            frmemp.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
            frmemp.show();

        } catch (Exception ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mnuempresaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jFacturacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem mnuUsuarios;
    private javax.swing.JMenuItem mnuempresa;
    // End of variables declaration//GEN-END:variables
}
